version: "3.1"
services:
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ../app/static/:/usr/share/nginx/html/static/
      - ../logs/nginx/:/var/log/nginx/
    networks:
      - nginx-load-balancer
      - internal
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - ../:/opt/ubo
      - /opt/ubo/app/assets/node_modules/
    networks:
      - internal
    restart: always
  node:
    image: node:12
    working_dir: /opt/ubo/assets
    volumes:
      - ../app:/opt/ubo
    networks:
      - internal
    # Use this to keep the container running
    tty: true
    restart: always
networks:
  internal:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
